name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - erddapy
  - panel
  - intake
  - pytest
  - pytest-cov
  - isort
  - flake8
  - pre-commit
  - types-setuptools
  - mypy
  - codecov
  - coverage[toml]
  - pip
  - pip:
    - cf-pandas
