name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - dask
  - pandas
  - erddapy
  - panel
  # - intake
  - pytest
  - pytest-cov
  - isort
  - flake8
  - pre-commit
  - types-setuptools
  - mypy
  - codecov
  - coverage[toml]
  - xarray
  - pip
  - pip:
    - git+https://github.com/intake/intake
    - cf-pandas
