name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - erddapy
  - panel
  - intake
  - pytest
  - pytest-cov
  - isort
  - flake8
  - pre-commit
  - types-setuptools
  - mypy
  - codecov
  - coverage[toml]
  - pip
  - pip:
    - git@github.com:axiom-data-science/cf-pandas.git

