name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - dask
  - pandas
  - erddapy
  - panel
  - intake
  - intake-xarray>=0.6.1
  - pytest
  - pytest-cov
  - isort
  - flake8
  - pre-commit
  - types-setuptools
  - mypy
  - codecov
  - coverage[toml]
  - pip
  - pip:
    - cf-pandas
